// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {settings} from '../models';
import {clip} from '../models';
import {snippet} from '../models';

export function AddToBlocklist(arg1:string):Promise<void>;

export function Clear():Promise<void>;

export function ClearAll():Promise<void>;

export function CursorPos():Promise<Array<number>>;

export function DecodeJWT(arg1:string):Promise<main.JWTDetails>;

export function DeleteItem(arg1:number):Promise<void>;

export function FormatItem(arg1:number):Promise<string>;

export function GetBlocklist():Promise<Array<string>>;

export function GetSettings():Promise<settings.Settings>;

export function Hide():Promise<void>;

export function History():Promise<Array<clip.ClipItem>>;

export function OpenDashboard():Promise<void>;

export function PasteFormatted(arg1:number):Promise<void>;

export function PasteItem(arg1:number):Promise<void>;

export function PasteMinified(arg1:number):Promise<void>;

export function PasteSnippet(arg1:number,arg2:Record<string, string>):Promise<void>;

export function PasteText(arg1:string):Promise<void>;

export function PasteTransformed(arg1:number,arg2:string):Promise<void>;

export function RemoveFromBlocklist(arg1:string):Promise<void>;

export function ReorderPins(arg1:Array<number>):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SnippetPlaceholders(arg1:number):Promise<Array<string>>;

export function Snippets():Promise<Array<snippet.Snippet>>;

export function TestHotkey(arg1:number,arg2:number):Promise<boolean>;

export function Thumbnail(arg1:number):Promise<string>;

export function TogglePin(arg1:number):Promise<void>;
