// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToBlocklist(arg1) {
  return window['go']['main']['App']['AddToBlocklist'](arg1);
}

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function ClearAll() {
  return window['go']['main']['App']['ClearAll']();
}

export function CursorPos() {
  return window['go']['main']['App']['CursorPos']();
}

export function DecodeJWT(arg1) {
  return window['go']['main']['App']['DecodeJWT'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function FormatItem(arg1) {
  return window['go']['main']['App']['FormatItem'](arg1);
}

export function GetBlocklist() {
  return window['go']['main']['App']['GetBlocklist']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function OpenDashboard() {
  return window['go']['main']['App']['OpenDashboard']();
}

export function PasteFormatted(arg1) {
  return window['go']['main']['App']['PasteFormatted'](arg1);
}

export function PasteItem(arg1) {
  return window['go']['main']['App']['PasteItem'](arg1);
}

export function PasteMinified(arg1) {
  return window['go']['main']['App']['PasteMinified'](arg1);
}

export function PasteSnippet(arg1, arg2) {
  return window['go']['main']['App']['PasteSnippet'](arg1, arg2);
}

export function PasteText(arg1) {
  return window['go']['main']['App']['PasteText'](arg1);
}

export function PasteTransformed(arg1, arg2) {
  return window['go']['main']['App']['PasteTransformed'](arg1, arg2);
}

export function RemoveFromBlocklist(arg1) {
  return window['go']['main']['App']['RemoveFromBlocklist'](arg1);
}

export function ReorderPins(arg1) {
  return window['go']['main']['App']['ReorderPins'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SnippetPlaceholders(arg1) {
  return window['go']['main']['App']['SnippetPlaceholders'](arg1);
}

export function Snippets() {
  return window['go']['main']['App']['Snippets']();
}

export function ValidateHotkey(arg1, arg2) {
  return window['go']['main']['App']['ValidateHotkey'](arg1, arg2);
}

export function Thumbnail(arg1) {
  return window['go']['main']['App']['Thumbnail'](arg1);
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}
