// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function CursorPos() {
  return window['go']['main']['App']['CursorPos']();
}

export function FormatItem(arg1) {
  return window['go']['main']['App']['FormatItem'](arg1);
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function PasteFormatted(arg1) {
  return window['go']['main']['App']['PasteFormatted'](arg1);
}

export function PasteItem(arg1) {
  return window['go']['main']['App']['PasteItem'](arg1);
}

export function PasteTransformed(arg1, arg2) {
  return window['go']['main']['App']['PasteTransformed'](arg1, arg2);
}

export function Thumbnail(arg1) {
  return window['go']['main']['App']['Thumbnail'](arg1);
}
