// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clip} from '../models';

export function Clear():Promise<void>;

export function CursorPos():Promise<Array<number>>;

export function Hide():Promise<void>;

export function History():Promise<Array<clip.ClipItem>>;

export function PasteItem(arg1:number):Promise<void>;
