// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function CursorPos() {
  return window['go']['main']['App']['CursorPos']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function PasteItem(arg1) {
  return window['go']['main']['App']['PasteItem'](arg1);
}

export function Thumbnail(arg1) {
  return window['go']['main']['App']['Thumbnail'](arg1);
}
